#dist_codes are a shorter hexidecimal representation of a 40-character binary vector
#the 40 character vector indicates the presence or absence of a taxon in a bioregion
#the first 35 represent the 35 lowest-rank bioregions; the last five are blank spots (always 0)
#refer to the print OUT to see what what bioregions each position represents
#get_all_dist.pl translates bioregion distribution strings into the binary vector and packs it into hex
#here we unpack the hex so we can store the binary vector values in a table
#the table is used by the online "checklist builder" pages

use lib "/Users/davidbaxter/DATA/eFlora";
use flatten;

open(OUT, ">outputs/load_distribution_table.sql") || die;

#process the bioregion hex code file, generated by get_all_dist.pl
open(IN, "outputs/dist_codes.txt") || die;
while(<IN>){
	$hex_code="";
	chomp;
	($hex_ID, $hex_code) = split(/\t/);
	$HEX{$hex_ID} = $hex_code;

	$dist_array = unpack("b*",pack("H*",$hex_code));
	@region_dist=split(//,$dist_array);
	#print join("\t",@hv[0 .. 34]), "\n";

	#format for SQLite insert (presence, i.e. "1", does not need to be changed)
	foreach (@region_dist) {
		s/0/NULL/;
	}

	print OUT "INSERT INTO eflora_distributions(TaxonID, CCo, CaRF, CaRH, nChI, sChI, DMojexcDMtns, DMtns, DSon, KR, MPexcWrn, NCo, NCoRH, NCoRI, NCoRO, PRexcSnJt, SCo, SCoRI, SCoRO, SNEexcWaI, nSNF, cSNF, sSNF, nSNH, cSNH, sSNH, ScV, SnBr, SnFrB, SnGb, SnJV, SnJt, Teh, WTR, WaI, Wrn)\n";
	print OUT "VALUES($hex_ID, ", join(", ",@region_dist[0 .. 34]), ")\n";
	print OUT ";\n";
}
close(IN);